# Generated by Django 4.2 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20260331_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointmentTime',
            field=models.CharField(
                blank=True,
                choices=[
                    ('08:00', '08:00'),
                    ('09:00', '09:00'),
                    ('10:00', '10:00'),
                    ('11:00', '11:00'),
                    ('13:00', '13:00'),
                    ('14:00', '14:00'),
                    ('15:00', '15:00'),
                    ('16:00', '16:00'),
                ],
                max_length=5,
                null=True,
            ),
        ),
    ]
